#!/usr/bin/env bash
# =============================================================================
# two-agent-system setup script
# Walks through Railway project creation, infrastructure, and service deploys.
# Run from: /Users/ilanben-brith/Development/two-agent-system
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo ""
echo "======================================================================"
echo "  two-agent-system — Railway setup"
echo "======================================================================"
echo ""

# --------------------------------------------------------------------------
# Step 1: Railway login
# --------------------------------------------------------------------------
echo "[1/8] Railway login"
echo "      Run: railway login"
echo "      This will open a browser window. Complete the auth flow."
echo ""
read -rp "Press Enter when you have logged in and are ready to continue..."
railway whoami

# --------------------------------------------------------------------------
# Step 2: Create the Railway project
# --------------------------------------------------------------------------
echo ""
echo "[2/8] Creating Railway project: two-agent-system"
railway init --name two-agent-system

echo ""
echo "  Project created. Now open the Railway dashboard to add infrastructure:"
echo "  https://railway.com/dashboard"
echo ""
echo "  Add the following services manually in the dashboard:"
echo "    1. PostgreSQL (Railway native add-on)"
echo "       After creation, open the Postgres service → Query tab → run:"
echo "         CREATE EXTENSION IF NOT EXISTS vector;"
echo ""
echo "    2. Qdrant (use the Railway template: search 'Qdrant')"
echo ""
read -rp "Press Enter when Postgres (with pgvector) and Qdrant are deployed and running..."

# --------------------------------------------------------------------------
# Step 3: Collect environment variables
# --------------------------------------------------------------------------
echo ""
echo "[3/8] Collecting required secrets and tokens"
echo ""

read -rp "  ARIA Telegram bot token (from @BotFather): " ARIA_TELEGRAM_TOKEN
read -rp "  ECHO Telegram bot token (from @BotFather): " ECHO_TELEGRAM_TOKEN
read -rp "  Telegram group chat ID (e.g. -100xxxxxxxxxx): " TELEGRAM_GROUP_CHAT_ID
read -rp "  Your Telegram user ID (the operator): " OPERATOR_TELEGRAM_ID
read -rp "  OpenRouter API key (from openrouter.ai): " OPENROUTER_API_KEY
read -rp "  Anthropic API key: " ANTHROPIC_API_KEY
read -rp "  OpenAI API key (used by Mem0 for embeddings): " OPENAI_API_KEY
read -rp "  Qdrant internal Railway hostname (e.g. qdrant.railway.internal): " QDRANT_HOST
read -rp "  Mem0 API URL (internal, e.g. http://mem0-api.railway.internal:8000): " MEM0_API_URL

# Generate shared secrets
OPENCLAW_GATEWAY_TOKEN=$(openssl rand -hex 32)
OPENCLAW_HOOKS_TOKEN=$(openssl rand -hex 32)
ECHO_AGENT_API_TOKEN=$(openssl rand -hex 32)
MEM0_API_KEY=$(openssl rand -hex 32)

echo ""
echo "  Generated secrets (save these somewhere safe):"
echo "    OPENCLAW_GATEWAY_TOKEN : $OPENCLAW_GATEWAY_TOKEN"
echo "    OPENCLAW_HOOKS_TOKEN   : $OPENCLAW_HOOKS_TOKEN"
echo "    ECHO_AGENT_API_TOKEN   : $ECHO_AGENT_API_TOKEN"
echo "    MEM0_API_KEY           : $MEM0_API_KEY"
echo ""
read -rp "Press Enter to continue (secrets are written to .env.secrets — do NOT commit this file)..."

cat > "$ROOT/.env.secrets" <<EOF
# Generated by setup.sh — DO NOT COMMIT
ARIA_TELEGRAM_TOKEN=$ARIA_TELEGRAM_TOKEN
ECHO_TELEGRAM_TOKEN=$ECHO_TELEGRAM_TOKEN
TELEGRAM_GROUP_CHAT_ID=$TELEGRAM_GROUP_CHAT_ID
OPERATOR_TELEGRAM_ID=$OPERATOR_TELEGRAM_ID
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
QDRANT_HOST=$QDRANT_HOST
MEM0_API_URL=$MEM0_API_URL
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
OPENCLAW_HOOKS_TOKEN=$OPENCLAW_HOOKS_TOKEN
ECHO_AGENT_API_TOKEN=$ECHO_AGENT_API_TOKEN
MEM0_API_KEY=$MEM0_API_KEY
EOF

echo "  Secrets written to .env.secrets"

# --------------------------------------------------------------------------
# Step 4: Deploy Mem0
# --------------------------------------------------------------------------
echo ""
echo "[4/8] Deploying Mem0 API service"

cd "$ROOT/mem0"
railway service create --name mem0-api
railway variables set \
  QDRANT_HOST="$QDRANT_HOST" \
  OPENAI_API_KEY="$OPENAI_API_KEY" \
  MEM0_API_KEY="$MEM0_API_KEY"
railway up --detach
cd "$ROOT"

echo "  Mem0 deployed. Wait ~60 seconds for it to be healthy before continuing."
read -rp "Press Enter when Mem0 is healthy (check Railway dashboard)..."

# --------------------------------------------------------------------------
# Step 5: Deploy ARIA (OpenClaw)
# --------------------------------------------------------------------------
echo ""
echo "[5/8] Deploying ARIA (OpenClaw)"

cd "$ROOT/aria"
railway service create --name aria
railway variables set \
  ARIA_TELEGRAM_TOKEN="$ARIA_TELEGRAM_TOKEN" \
  TELEGRAM_GROUP_CHAT_ID="$TELEGRAM_GROUP_CHAT_ID" \
  OPERATOR_TELEGRAM_ID="$OPERATOR_TELEGRAM_ID" \
  OPENROUTER_API_KEY="$OPENROUTER_API_KEY" \
  ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  MEM0_API_URL="$MEM0_API_URL" \
  MEM0_API_KEY="$MEM0_API_KEY" \
  OPENCLAW_GATEWAY_TOKEN="$OPENCLAW_GATEWAY_TOKEN" \
  OPENCLAW_HOOKS_TOKEN="$OPENCLAW_HOOKS_TOKEN" \
  ECHO_AGENT_API_TOKEN="$ECHO_AGENT_API_TOKEN" \
  ECHO_INTERNAL_URL="http://echo.railway.internal:3001"
railway up --detach
cd "$ROOT"

echo "  ARIA deployed."

# --------------------------------------------------------------------------
# Step 6: Deploy ECHO (NanoClaw)
# --------------------------------------------------------------------------
echo ""
echo "[6/8] Deploying ECHO (NanoClaw)"

cd "$ROOT/echo"
railway service create --name echo
railway variables set \
  ECHO_TELEGRAM_TOKEN="$ECHO_TELEGRAM_TOKEN" \
  TELEGRAM_GROUP_CHAT_ID="$TELEGRAM_GROUP_CHAT_ID" \
  OPERATOR_TELEGRAM_ID="$OPERATOR_TELEGRAM_ID" \
  ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  MEM0_API_URL="$MEM0_API_URL" \
  MEM0_API_KEY="$MEM0_API_KEY" \
  ECHO_AGENT_API_TOKEN="$ECHO_AGENT_API_TOKEN" \
  ARIA_HOOKS_TOKEN="$OPENCLAW_HOOKS_TOKEN" \
  ARIA_INTERNAL_URL="http://aria.railway.internal:18789" \
  AGENT_API_PORT="3001"
railway up --detach
cd "$ROOT"

echo "  ECHO deployed."

# --------------------------------------------------------------------------
# Step 7: Post-deploy OpenClaw plugin install
# --------------------------------------------------------------------------
echo ""
echo "[7/8] Post-deploy: install Mem0 plugin on ARIA"
echo ""
echo "  SSH or exec into the ARIA service container and run:"
echo "    openclaw plugins install @mem0/openclaw-mem0"
echo "    openclaw gateway restart"
echo ""
echo "  Or use Railway's exec feature in the dashboard."
read -rp "Press Enter when done..."

# --------------------------------------------------------------------------
# Step 8: Verification checklist
# --------------------------------------------------------------------------
echo ""
echo "[8/8] Verification checklist"
echo ""
echo "  Run each of these and confirm the expected result:"
echo ""
echo "  1. Private chat with ARIA (@YourARIABot):"
echo "     Send: 'hello'"
echo "     Expected: ARIA responds directly, no routing discussion, MiMo-V2-Pro active"
echo ""
echo "  2. Private chat with ECHO (@YourECHOBot):"
echo "     Send: 'hello'"
echo "     Expected: ECHO responds directly, no routing discussion, Claude Sonnet 4.6 active"
echo ""
echo "  3. Group chat — unaddressed message:"
echo "     Send: 'summarize last week in tech'"
echo "     Expected: ARIA proposes a routing assessment, ECHO responds, they debate and converge"
echo ""
echo "  4. Group chat — explicit addressing:"
echo "     Send: '@ARIA what can you do?'"
echo "     Expected: ARIA responds immediately, ECHO stays silent"
echo ""
echo "  5. Group chat — explicit addressing:"
echo "     Send: '@ECHO what can you do?'"
echo "     Expected: ECHO responds immediately, ARIA stays silent"
echo ""
echo "  6. Memory check (after any task):"
echo "     Ask ARIA: 'what do you remember from our conversation?'"
echo "     Ask ECHO: 'what do you remember from our conversation?'"
echo "     Expected: Both recall memories tagged with their respective agent_id"
echo ""
echo "  7. ECHO health endpoint:"
echo "     From Railway exec on echo service:"
echo "       curl http://localhost:3001/health"
echo "     Expected: {\"status\":\"ok\",\"agent\":\"echo\"}"
echo ""
echo "======================================================================"
echo "  Setup complete!"
echo "  Constitutions can be edited at:"
echo "    aria/ARIA_CONSTITUTION.md"
echo "    echo/ECHO_CONSTITUTION.md (also echo/CLAUDE.md)"
echo "  To change CONSENSUS_TIMEOUT: edit the line 'CONSENSUS_TIMEOUT: 5 minutes'"
echo "  in both constitution files, then: railway up (from each service directory)"
echo "======================================================================"
